name: Ansible Dev Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
      
    - name: Prepare SSH
      run: |
        mkdir ~/.ssh
        echo "${{secrets.PRIVATE_SSH_KEY}}" | tr -d '\r' > ~/.ssh/id_rsa
        echo "${{secrets.PUBLIC_SSH_KEY}}" | tr -d '\r' > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
    
    - name: Check Ansible Linting
      run: |
        sudo apt-get install -y ansible-lint
        ansible-lint roles/httpserver/tasks/main.yml
        ansible-lint roles/dbserver/tasks/main.yml
    
    - name: Check Dev Roles
      run: ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts dev-site.yml


